In [ ]:
if 5<3:
  print("yes")
  c=3
  x=7
  m=c+x
  print(m)
print("end")

end

In [ ]:
def xyz():
  print("yes")
  c=3
  x=7
  m=c+x
  print(m)

In [ ]:
xyz()

yes
10

In [ ]:
def mnp(m):
  k=10
  c=m+k
  print(c)

In [ ]:
mnp(9)

19

In [ ]:
def mnp(m,n,p='mango'):
  print(p)

In [ ]:
mnp(9,12)

mango

In [ ]:
type(100)

int

In [ ]:
def newf():
  print(100)
  print(200)
newf()

100
200

In [ ]:
def newf():
  print(100)
  print(200)
  return 150
newf()

100
200

150

In [ ]:
def onef(x):
  return x*7 +23

In [ ]:
twof=lambda x: x*7+23

In [ ]:
twof(5)

58

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pd.DataFrame({
    "A":[10,20,30,40,50],
    "b":['a','b','c','d','e']
})

    A  b
0  10  a
1  20  b
2  30  c
3  40  d
4  50  e

In [ ]:
pd.DataFrame({
    "A":[10,20,30,40,50],
    "b":['a','b','c','d','e']
})

    A  b
0  10  a
1  20  b
2  30  c
3  40  d
4  50  e

In [ ]:
pd.DataFrame({
    "A":[10,20,30,40,50],
    "b":['a','b','c','d','e'],
    "c":np.random.randint(65)
})

    A  b   c
0  10  a  30
1  20  b  30
2  30  c  30
3  40  d  30
4  50  e  30

In [ ]:
pd.DataFrame(
    np.random.randint(0,9,(10,4)),columns=["a","b","c","d"]
)

   a  b  c  d
0  6  0  2  4
1  5  1  5  2
2  2  4  7  4
3  7  3  3  2
4  5  2  4  2
5  4  3  3  0
6  5  7  5  3
7  1  2  6  3
8  1  2  5  0
9  7  7  0  0

In [ ]:
np.random.rand(10,3)

array([[0.20469421, 0.24535163, 0.72103137],
       [0.78774242, 0.63825715, 0.4496958 ],
       [0.56112181, 0.25932486, 0.40846077],
       [0.57584171, 0.56709738, 0.47073774],
       [0.70321513, 0.17896703, 0.85123747],
       [0.08341332, 0.04747961, 0.94145738],
       [0.92111952, 0.18713407, 0.02194627],
       [0.22045641, 0.67737329, 0.70071827],
       [0.73362159, 0.60833389, 0.15797113],
       [0.48606624, 0.12324889, 0.0296366 ]])

In [ ]:
np.random.rand(10,3).round(2)

array([[0.05, 0.74, 0.24],
       [0.47, 0.3 , 0.77],
       [0.51, 0.1 , 0.88],
       [0.85, 0.38, 0.72],
       [0.02, 0.86, 0.76],
       [0.69, 0.68, 0.66],
       [0.73, 0.85, 0.99],
       [0.  , 0.08, 0.7 ],
       [0.87, 0.94, 0.75],
       [0.25, 0.74, 0.26]])

In [ ]:
dfx=pd.DataFrame(
    np.random.rand(10,3).round(2),columns=["a","b","c"]
)

In [ ]:
dfx.to_excel("abc.xlsx")

In [ ]:
pd.read_excel("abc.xlsx")

   Unnamed: 0     a     b     c
0           0  0.68  0.65  0.84
1           1  0.45  0.56  0.99
2           2  0.08  0.81  0.93
3           3  0.19  0.77  0.38
4           4  0.84  0.99  0.82
5           5  0.48  0.78  0.91
6           6  0.57  0.22  0.02
7           7  0.86  0.93  0.50
8           8  0.74  0.30  0.77
9           9  0.08  0.76  1.00

In [ ]:
pd.read_excel("abc.xlsx",index_col="Unnamed: 0")

      a     b     c
0  0.68  0.65  0.84
1  0.45  0.56  0.99
2  0.08  0.81  0.93
3  0.19  0.77  0.38
4  0.84  0.99  0.82
5  0.48  0.78  0.91
6  0.57  0.22  0.02
7  0.86  0.93  0.50
8  0.74  0.30  0.77
9  0.08  0.76  1.00

In [ ]:
import pandas as pd
import numpy as np
dfx=pd.DataFrame(
    np.random.rand(10,3).round(2),columns=["a","b","c"]
)
dfx.iloc[2,1]

np.float64(0.51)

In [ ]:
dfx['d']=np.random.randint(0,10,10)

In [ ]:
dfx.describe(include="all")

               a          b          c         d
count  10.000000  10.000000  10.000000  10.00000
mean    0.613000   0.570000   0.442000   4.60000
std     0.347852   0.264491   0.305061   2.54733
min     0.030000   0.120000   0.070000   1.00000
25%     0.310000   0.510000   0.170000   2.50000
50%     0.700000   0.595000   0.395000   4.50000
75%     0.902500   0.745000   0.732500   6.50000
max     0.970000   0.980000   0.850000   9.00000

In [ ]:
dfx['m']=np.random.choice(['a','b','c','d','e'],10)

In [ ]:
dfx.drop('m',axis=1,inplace=True)

How to create a conditions to create a new column

In [ ]:
dfx['dd']= dfx['d'].apply(lambda x:'big' if x>5 else 'small')

In [ ]:
dfx

      a     b     c  d     dd
0  0.77  0.77  0.31  2  small
1  0.97  0.77  0.80  9    big
2  0.20  0.51  0.48  4  small
3  0.93  0.12  0.07  5  small
4  0.63  0.51  0.14  7    big
5  0.96  0.67  0.85  4  small
6  0.03  0.18  0.26  2  small
7  0.82  0.66  0.65  5  small
8  0.21  0.98  0.10  7    big
9  0.61  0.53  0.76  1  small

In [ ]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
dfx.set_index(np.arange(1,100,10))

       a     b     c  d     dd
1   0.77  0.77  0.31  2  small
11  0.97  0.77  0.80  9    big
21  0.20  0.51  0.48  4  small
31  0.93  0.12  0.07  5  small
41  0.63  0.51  0.14  7    big
51  0.96  0.67  0.85  4  small
61  0.03  0.18  0.26  2  small
71  0.82  0.66  0.65  5  small
81  0.21  0.98  0.10  7    big
91  0.61  0.53  0.76  1  small

In [ ]:
dfx.loc[4,'b']

np.float64(0.51)

In [ ]:
dfx.iloc[2,2]

np.float64(0.48)

range of index

In [ ]:
st="this is python"

In [ ]:
st[2:8]
'is is'

'is is'

In [ ]:
ar=np.random.randint(11,99,(4,5,6))

In [ ]:
ar

array([[[56, 59, 30, 34, 94, 26],
        [89, 79, 22, 74, 64, 49],
        [19, 90, 31, 67, 45, 27],
        [95, 59, 24, 82, 66, 76],
        [69, 92, 97, 60, 25, 74]],

       [[42, 70, 58, 90, 67, 28],
        [14, 19, 89, 49, 97, 50],
        [43, 39, 69, 15, 34, 91],
        [52, 67, 91, 74, 11, 72],
        [27, 47, 11, 37, 86, 51]],

       [[42, 26, 39, 81, 32, 66],
        [60, 13, 45, 39, 49, 35],
        [16, 80, 34, 18, 70, 45],
        [90, 84, 98, 15, 82, 44],
        [66, 52, 45, 98, 81, 28]],

       [[49, 22, 63, 56, 83, 54],
        [77, 68, 56, 74, 43, 87],
        [27, 45, 74, 93, 55, 22],
        [58, 52, 86, 81, 82, 95],
        [35, 37, 57, 51, 54, 51]]])

In [ ]:
ar[1,2,:]

array([43, 39, 69, 15, 34, 91])

In [ ]:
ar[2,:,:]

array([[42, 26, 39, 81, 32, 66],
       [60, 13, 45, 39, 49, 35],
       [16, 80, 34, 18, 70, 45],
       [90, 84, 98, 15, 82, 44],
       [66, 52, 45, 98, 81, 28]])

In [ ]:
ar[2,:,2].shape

(5,)

# **for two dimensions**

In [ ]:
ar2=np.random.randint(11,99,(7,5))

In [ ]:
ar2[2,3].shape

()

In [ ]:
newar=np.zeros((7,3,5,9))
newar.shape

(7, 3, 5, 9)

In [ ]:
newar[:,:,2,3].shape

(7, 3)

In [ ]:
newar[2,1,2,3].shape

()

In [ ]:
newar[2,1,2,2:6].shape

(4,)

In [ ]:
newar[2:5,1:3,2:4,2:6].shape

(3, 2, 2, 4)

## **range of index in pandas**

In [ ]:
ndf=pd.DataFrame({
    "first":np.random.randint(11,99,10),
    "second":np.random.randint(11,99,10),
    "third":np.random.randint(11,99,10),
    "fourth":np.random.randint(11,99,10),
    "fifth":np.random.randint(11,99,10),
})
ndf

   first  second  third  fourth  fifth
0     80      46     73      80     57
1     15      47     16      47     47
2     69      91     83      45     32
3     40      81     53      51     70
4     31      40     83      77     57
5     79      44     15      46     35
6     26      92     37      35     82
7     91      84     24      47     68
8     50      79     87      80     38
9     98      74     51      11     26

In [ ]:
ndf.loc[1,"second"]

np.int64(47)

In [ ]:
ndf.iloc[5,1]
np.int64(50)

np.int64(50)

In [ ]:
ndf.iloc[6,:]#restricted to sixth rows but all of the columns

first     26
second    92
third     37
fourth    35
fifth     82
Name: 6, dtype: int64

In [ ]:
ndf.iloc[:,2]#all o fthe rows and restricted to second column

0    73
1    16
2    83
3    53
4    83
5    15
6    37
7    24
8    87
9    51
Name: third, dtype: int64

In [ ]:
ndf.iloc[3:8,2:4]

   third  fourth
3     53      51
4     83      77
5     15      46
6     37      35
7     24      47