In [ ]:

import pandas as pd
import numpy as np

In [ ]:
import sklearn

In [ ]:
from sklearn.datasets import make_regression, load_iris

# **Using Load based datasets**

In [ ]:
load_iris().keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
dt = load_iris()

In [ ]:
dt.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame(dt.data, columns=dt.feature_names)

In [ ]:
make_regression(n_samples=20,n_features=4,bias=10.3,noise=1.8)

(array([[ 0.33559276,  0.79076402, -0.39518332,  0.58431651],
        [ 0.96998887, -0.70271244,  0.02806534,  0.91606458],
        [ 0.18551779, -0.29652583,  0.50221353, -0.33097838],
        [-0.26343901,  1.17060652, -0.10436482, -0.96665549],
        [ 0.28974631,  0.60573758,  0.60407848,  2.7156068 ],
        [ 1.31315573, -1.01431681,  1.67217624, -0.08314841],
        [ 0.22239964, -2.53682187, -0.3479793 ,  0.4948272 ],
        [-0.87575037,  0.32527623,  0.51047033, -0.2970649 ],
        [-0.31679298, -0.41917075, -1.65130178,  0.70842314],
        [-0.48857732,  1.05315595, -0.36094935,  0.99247423],
        [-0.40577795, -1.17934725, -0.58475776,  0.62464511],
        [ 1.77432727, -0.82585898, -0.17054466,  0.23258921],
        [ 0.26239058, -1.66501441, -0.45426188,  0.81894518],
        [-0.20043567,  0.31937797, -0.24030142,  0.49483466],
        [ 1.45498751,  1.50986189, -0.10772748, -1.29196241],
        [ 0.97498283,  1.12728043, -0.37067312, -2.62223118],
        [-0.19738613,  0.5457709 , -1.08595477, -0.47398032],
        [-0.86475277, -0.54556541,  1.55909731, -1.55282708],
        [ 0.08680861,  0.10770759, -0.2402952 ,  0.14719944],
        [ 0.61951521, -0.45980679, -0.82421852,  1.26181513]]),
 array([  73.20145192,   62.53180089,   19.93575343,   11.74166094,
         221.43642797,  117.60345094, -118.61645171,    9.57351149,
         -96.01147272,   70.10840591,  -76.60799   ,   50.57928346,
         -60.34484973,   26.58162745,   96.65052718,  -23.58542503,
         -55.08735716,  -33.36487334,   13.56845126,   17.32012953]))

In [ ]:
df.rename(columns={'sepal length (cm)':'sepal_length', 'sepal width (cm)':'sepal_width', 'petal length (cm)':'petal_length', 'petal width (cm)':'petal_width'}, inplace=True)

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
df['target'] = dt.target

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [ ]:

df[df['sepal_length']>5]

     sepal_length  sepal_width  petal_length  petal_width  target
0             5.1          3.5           1.4          0.2       0
5             5.4          3.9           1.7          0.4       0
10            5.4          3.7           1.5          0.2       0
14            5.8          4.0           1.2          0.2       0
15            5.7          4.4           1.5          0.4       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[118 rows x 5 columns]

In [ ]:
df.loc[df['sepal_length']>5, ['sepal_length', 'sepal_width']]

     sepal_length  sepal_width
0             5.1          3.5
5             5.4          3.9
10            5.4          3.7
14            5.8          4.0
15            5.7          4.4
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[118 rows x 2 columns]

In [ ]:
df.loc[df['sepal_length']>5, ['sepal_length', 'sepal_width']]

     sepal_length  sepal_width
0             5.1          3.5
5             5.4          3.9
10            5.4          3.7
14            5.8          4.0
15            5.7          4.4
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[118 rows x 2 columns]

In [ ]:
df.loc[df['sepal_length']>= 6, 'new_column'] = 'big sepals'

In [ ]:
df.loc[df['sepal_length']>= 6, 'new_column'] = 'big sepals'

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width  target  new_column
0             5.1          3.5           1.4          0.2       0         NaN
1             4.9          3.0           1.4          0.2       0         NaN
2             4.7          3.2           1.3          0.2       0         NaN
3             4.6          3.1           1.5          0.2       0         NaN
4             5.0          3.6           1.4          0.2       0         NaN
..            ...          ...           ...          ...     ...         ...
145           6.7          3.0           5.2          2.3       2  big sepals
146           6.3          2.5           5.0          1.9       2  big sepals
147           6.5          3.0           5.2          2.0       2  big sepals
148           6.2          3.4           5.4          2.3       2  big sepals
149           5.9          3.0           5.1          1.8       2         NaN

[150 rows x 6 columns]

# **Using Make_based dataset**

In [ ]:
x,y=make_regression(n_samples=20,n_features=4,bias=10.3,noise=1.8)

In [ ]:
x.shape

(20, 4)

In [ ]:
y.shape

(20,)

In [ ]:
pd.DataFrame(x)

           0         1         2         3
0  -1.192159  0.003451  0.306685  0.946212
1   1.650605  1.195804 -0.990316 -0.145264
2  -0.667442  1.397722  0.398165 -0.327615
3  -0.109745 -0.171234  1.624319 -0.245908
4  -0.386153 -0.444399  2.132186  0.734833
5  -0.609973 -0.362718 -0.781679  0.872985
6  -0.992667  0.314592  0.017371 -1.074648
7  -0.151475  0.376706  1.209396  0.830726
8   0.023303  0.965436 -0.561407  0.722405
9   0.406074 -0.780977  1.398384  0.157893
10  1.678989 -1.209150  0.001852 -0.438931
11  0.298519  0.809823 -0.228463 -0.878773
12 -0.519714 -1.559461  0.564701  1.738906
13  0.384540 -0.988628  1.103984 -1.620453
14 -0.225180  0.537565  0.507017 -2.524946
15  0.006921 -1.321117 -0.793162 -0.148120
16  1.012504  0.105132 -1.006313 -0.236211
17 -0.088414  1.118504  0.965705  0.410678
18 -0.393662 -0.714427 -1.329869 -2.243696
19  1.955675  0.104040  0.510263 -0.984822

In [ ]:
pd.DataFrame(x).round(2)

       0     1     2     3
0  -1.19  0.00  0.31  0.95
1   1.65  1.20 -0.99 -0.15
2  -0.67  1.40  0.40 -0.33
3  -0.11 -0.17  1.62 -0.25
4  -0.39 -0.44  2.13  0.73
5  -0.61 -0.36 -0.78  0.87
6  -0.99  0.31  0.02 -1.07
7  -0.15  0.38  1.21  0.83
8   0.02  0.97 -0.56  0.72
9   0.41 -0.78  1.40  0.16
10  1.68 -1.21  0.00 -0.44
11  0.30  0.81 -0.23 -0.88
12 -0.52 -1.56  0.56  1.74
13  0.38 -0.99  1.10 -1.62
14 -0.23  0.54  0.51 -2.52
15  0.01 -1.32 -0.79 -0.15
16  1.01  0.11 -1.01 -0.24
17 -0.09  1.12  0.97  0.41
18 -0.39 -0.71 -1.33 -2.24
19  1.96  0.10  0.51 -0.98

In [ ]:
df=pd.DataFrame(x).round(2)

In [ ]:
df.columns=["col1","col2","col3","col4"]

In [ ]:
df.rename(columns={
    "col1":"delhi",
    "col2":"mumbai",
    "col3":"karnataka",
    "col4":"andhra",
},inplace=True)

In [ ]:
df

    delhi  mumbai  karnataka  andhra
0   -1.19    0.00       0.31    0.95
1    1.65    1.20      -0.99   -0.15
2   -0.67    1.40       0.40   -0.33
3   -0.11   -0.17       1.62   -0.25
4   -0.39   -0.44       2.13    0.73
5   -0.61   -0.36      -0.78    0.87
6   -0.99    0.31       0.02   -1.07
7   -0.15    0.38       1.21    0.83
8    0.02    0.97      -0.56    0.72
9    0.41   -0.78       1.40    0.16
10   1.68   -1.21       0.00   -0.44
11   0.30    0.81      -0.23   -0.88
12  -0.52   -1.56       0.56    1.74
13   0.38   -0.99       1.10   -1.62
14  -0.23    0.54       0.51   -2.52
15   0.01   -1.32      -0.79   -0.15
16   1.01    0.11      -1.01   -0.24
17  -0.09    1.12       0.97    0.41
18  -0.39   -0.71      -1.33   -2.24
19   1.96    0.10       0.51   -0.98

In [ ]:
pd.date_range("04-07-20",periods=10,freq='m')

/tmp/ipykernel_854/3963483011.py:1: FutureWarning: 'm' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range("04-07-20",periods=10,freq='m')

DatetimeIndex(['2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31',
               '2020-08-31', '2020-09-30', '2020-10-31', '2020-11-30',
               '2020-12-31', '2021-01-31'],
              dtype='datetime64[ns]', freq='ME')

In [ ]:
df.set_index(pd.date_range("04-07-20",periods=20,freq="d"),inplace=True)
df

            delhi  mumbai  karnataka  andhra
2020-04-07  -1.19    0.00       0.31    0.95
2020-04-08   1.65    1.20      -0.99   -0.15
2020-04-09  -0.67    1.40       0.40   -0.33
2020-04-10  -0.11   -0.17       1.62   -0.25
2020-04-11  -0.39   -0.44       2.13    0.73
2020-04-12  -0.61   -0.36      -0.78    0.87
2020-04-13  -0.99    0.31       0.02   -1.07
2020-04-14  -0.15    0.38       1.21    0.83
2020-04-15   0.02    0.97      -0.56    0.72
2020-04-16   0.41   -0.78       1.40    0.16
2020-04-17   1.68   -1.21       0.00   -0.44
2020-04-18   0.30    0.81      -0.23   -0.88
2020-04-19  -0.52   -1.56       0.56    1.74
2020-04-20   0.38   -0.99       1.10   -1.62
2020-04-21  -0.23    0.54       0.51   -2.52
2020-04-22   0.01   -1.32      -0.79   -0.15
2020-04-23   1.01    0.11      -1.01   -0.24
2020-04-24  -0.09    1.12       0.97    0.41
2020-04-25  -0.39   -0.71      -1.33   -2.24
2020-04-26   1.96    0.10       0.51   -0.98

In [ ]:
df.to_excel("regression.xlsx")

In [ ]:
pd.read_excel("regression2.xlsx")

   Unnamed: 0  delhi  mumbai  karnataka  andhra
0  2020-04-07  -1.19    0.00       0.31    0.95
1  2020-04-08   1.65    1.20      -0.99   -0.15
2  2020-04-09  -0.67    1.40       0.40   -0.33
3  2020-04-10  -0.11   -0.17       1.62   -0.25
4  2020-04-11  -0.39   -0.44       2.13    0.73
5  2020-04-12  -0.61   -0.36      -0.78    0.87
6  2020-04-13  -0.99    0.31       0.02   -1.07
7  2020-04-14  -0.15    0.38       1.21    0.83
8  2020-04-15   0.02    0.97      -0.56    0.72
9  2020-04-16   0.41   -0.78       1.40    0.16
10 2020-04-17   1.68   -1.21       0.00   -0.44
11 2020-04-18   0.30    0.81      -0.23   -0.88
12 2020-04-19  -0.52   -1.56       0.56    1.74
13 2020-04-20   0.38   -0.99       1.10   -1.62
14 2020-04-21  -0.23    0.54       0.51   -2.52
15 2020-04-22   0.01   -1.32      -0.79   -0.15
16 2020-04-23   1.01    0.11      -1.01   -0.24
17 2020-04-24  -0.09    1.12       0.97    0.41
18 2020-04-25  -0.39   -0.71      -1.33   -2.24
19 2020-04-26   1.96    0.10       0.51   -0.98

In [ ]:
ndf=pd.read_excel("regression2.xlsx",index_col="Unnamed: 0")

In [ ]:
ndf

            delhi  mumbai  karnataka  andhra
2020-04-07  -1.19    0.00       0.31    0.95
2020-04-08   1.65    1.20      -0.99   -0.15
2020-04-09  -0.67    1.40       0.40   -0.33
2020-04-10  -0.11   -0.17       1.62   -0.25
2020-04-11  -0.39   -0.44       2.13    0.73
2020-04-12  -0.61   -0.36      -0.78    0.87
2020-04-13  -0.99    0.31       0.02   -1.07
2020-04-14  -0.15    0.38       1.21    0.83
2020-04-15   0.02    0.97      -0.56    0.72
2020-04-16   0.41   -0.78       1.40    0.16
2020-04-17   1.68   -1.21       0.00   -0.44
2020-04-18   0.30    0.81      -0.23   -0.88
2020-04-19  -0.52   -1.56       0.56    1.74
2020-04-20   0.38   -0.99       1.10   -1.62
2020-04-21  -0.23    0.54       0.51   -2.52
2020-04-22   0.01   -1.32      -0.79   -0.15
2020-04-23   1.01    0.11      -1.01   -0.24
2020-04-24  -0.09    1.12       0.97    0.41
2020-04-25  -0.39   -0.71      -1.33   -2.24
2020-04-26   1.96    0.10       0.51   -0.98

In [ ]:
ndf.loc[:,"delhi"]

2020-04-07   -1.19
2020-04-08    1.65
2020-04-09   -0.67
2020-04-10   -0.11
2020-04-11   -0.39
2020-04-12   -0.61
2020-04-13   -0.99
2020-04-14   -0.15
2020-04-15    0.02
2020-04-16    0.41
2020-04-17    1.68
2020-04-18    0.30
2020-04-19   -0.52
2020-04-20    0.38
2020-04-21   -0.23
2020-04-22    0.01
2020-04-23    1.01
2020-04-24   -0.09
2020-04-25   -0.39
2020-04-26    1.96
Name: delhi, dtype: float64

In [ ]:
ndf[ndf["delhi"]>0]

            delhi  mumbai  karnataka  andhra
2020-04-08   1.65    1.20      -0.99   -0.15
2020-04-15   0.02    0.97      -0.56    0.72
2020-04-16   0.41   -0.78       1.40    0.16
2020-04-17   1.68   -1.21       0.00   -0.44
2020-04-18   0.30    0.81      -0.23   -0.88
2020-04-20   0.38   -0.99       1.10   -1.62
2020-04-22   0.01   -1.32      -0.79   -0.15
2020-04-23   1.01    0.11      -1.01   -0.24
2020-04-26   1.96    0.10       0.51   -0.98

In [ ]:
ndf[(ndf["delhi"]>0)&(ndf["mumbai"])]

            delhi  mumbai  karnataka  andhra
2020-04-08   1.65    1.20      -0.99   -0.15
2020-04-15   0.02    0.97      -0.56    0.72
2020-04-16   0.41   -0.78       1.40    0.16
2020-04-17   1.68   -1.21       0.00   -0.44
2020-04-18   0.30    0.81      -0.23   -0.88
2020-04-20   0.38   -0.99       1.10   -1.62
2020-04-22   0.01   -1.32      -0.79   -0.15
2020-04-23   1.01    0.11      -1.01   -0.24
2020-04-26   1.96    0.10       0.51   -0.98